[package]
name = "himalaya"
description = "📫 Minimalist CLI email client"
version = "0.1.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
imap = "2.4.0"
lettre = "0.10.0-alpha.4"
mailparse = "0.13.1"
native-tls = "0.2"
rfc2047-decoder = "0.1.2"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
terminal_size = "0.1.15"
toml = "0.5.8"
uuid = { version = "0.8", features = ["v4"] }
