[package]
name = "himalaya"
description = "📫 Minimalist CLI mail client"
version = "0.1.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imap = "2.4.0"
native-tls = "0.2"
serde = { version = "1.0.118", features = ["derive"] }
toml = "0.5.8"
